-- =============================================================================
-- VipCleaners POS — Esquema base PostgreSQL
-- Reemplaza a schema.sql (MySQL), que estaba desincronizado con la base viva.
-- Esta es la ÚNICA fuente de verdad del esquema. Nada de DDL manual.
-- =============================================================================

-- ---------- Extensiones ------------------------------------------------------
-- pgcrypto: gen_random_bytes(), usado por el script de migración desde MySQL
-- para generar los tokens de seguimiento de las órdenes históricas.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------- Tipos enumerados -------------------------------------------------
CREATE TYPE rol_usuario         AS ENUM ('admin', 'empleado', 'cliente');
CREATE TYPE tipo_identificacion AS ENUM ('INE', 'Pasaporte', 'Licencia', 'Otra');
CREATE TYPE metodo_pago         AS ENUM ('efectivo', 'tarjeta', 'transferencia', 'mercado_pago');
CREATE TYPE estado_pago_orden   AS ENUM ('pendiente', 'parcial', 'pagado', 'reembolsado');
CREATE TYPE estado_pago         AS ENUM ('pendiente', 'procesando', 'completado', 'rechazado', 'reembolsado');
CREATE TYPE origen_orden        AS ENUM ('pos', 'online');
CREATE TYPE tipo_direccion      AS ENUM ('domicilio', 'pickup', 'facturacion', 'otro');
CREATE TYPE tipo_movimiento_inv AS ENUM ('entrada', 'salida', 'ajuste', 'merma', 'devolucion');
CREATE TYPE tipo_archivo        AS ENUM ('calzado_entrada', 'calzado_salida', 'identificacion', 'otro');
CREATE TYPE entidad_archivo     AS ENUM ('orden', 'cliente', 'empleado', 'producto', 'servicio', 'marca');
CREATE TYPE estado_consulta     AS ENUM ('pendiente', 'en_proceso', 'respondida', 'cerrada');
CREATE TYPE accion_log          AS ENUM ('crear', 'actualizar', 'eliminar', 'login', 'logout', 'otro');
CREATE TYPE estado_corte        AS ENUM ('abierto', 'cerrado');

-- ---------- Trigger genérico de fecha_actualizacion --------------------------
CREATE OR REPLACE FUNCTION set_fecha_actualizacion()
RETURNS TRIGGER AS $fn$
BEGIN
  NEW.fecha_actualizacion = now();
  RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;

-- =============================================================================
-- Identidad y personal
-- =============================================================================
CREATE TABLE usuarios (
  usuario_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email               VARCHAR(160) NOT NULL,
  password            VARCHAR(255) NOT NULL,
  rol                 rol_usuario  NOT NULL,
  token_recuperacion  VARCHAR(255) NULL,
  expiracion_token    TIMESTAMPTZ  NULL,
  intentos_fallidos   INT          NOT NULL DEFAULT 0,
  bloqueado_hasta     TIMESTAMPTZ  NULL,
  ultimo_acceso       TIMESTAMPTZ  NULL,
  activo              BOOLEAN      NOT NULL DEFAULT TRUE,
  fecha_creacion      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- El correo se normaliza a minúsculas en la app; el índice único lo garantiza.
CREATE UNIQUE INDEX ux_usuario_email ON usuarios (lower(email));
CREATE INDEX idx_usuario_rol ON usuarios (rol) WHERE activo;
CREATE TRIGGER trg_usuarios_upd BEFORE UPDATE ON usuarios
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE empleados (
  empleado_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id            INT NOT NULL UNIQUE REFERENCES usuarios(usuario_id) ON DELETE CASCADE,
  nombre                VARCHAR(100) NOT NULL,
  apellidos             VARCHAR(100) NOT NULL DEFAULT '',
  telefono              VARCHAR(20)  NULL,
  direccion             TEXT         NULL,
  codigo_postal         VARCHAR(10)  NULL,
  ciudad                VARCHAR(80)  NULL,
  estado                VARCHAR(80)  NULL,
  pais                  VARCHAR(80)  NOT NULL DEFAULT 'México',
  fecha_nacimiento      DATE         NULL,
  numero_identificacion VARCHAR(60)  NULL,
  tipo_id               tipo_identificacion NULL,
  fecha_contratacion    DATE         NULL,
  puesto                VARCHAR(60)  NULL,
  salario               NUMERIC(10,2) NULL,
  activo                BOOLEAN      NOT NULL DEFAULT TRUE,
  fecha_creacion        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  fecha_actualizacion   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_empleado_nombre ON empleados (nombre, apellidos);
CREATE TRIGGER trg_empleados_upd BEFORE UPDATE ON empleados
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE clientes (
  cliente_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id          INT NULL REFERENCES usuarios(usuario_id) ON DELETE SET NULL,
  nombre              VARCHAR(100) NOT NULL,
  apellidos           VARCHAR(100) NOT NULL DEFAULT '',
  telefono            VARCHAR(20)  NULL,
  email               VARCHAR(160) NULL,
  direccion           TEXT         NULL,
  codigo_postal       VARCHAR(10)  NULL,
  ciudad              VARCHAR(80)  NULL,
  estado              VARCHAR(80)  NULL,
  pais                VARCHAR(80)  NOT NULL DEFAULT 'México',
  fecha_nacimiento    DATE         NULL,
  puntos_fidelidad    INT          NOT NULL DEFAULT 0,
  -- Datos fiscales para CFDI
  rfc                 VARCHAR(13)  NULL,
  razon_social        VARCHAR(255) NULL,
  regimen_fiscal      VARCHAR(10)  NULL,
  uso_cfdi            VARCHAR(10)  NULL,
  cp_fiscal           VARCHAR(10)  NULL,
  notas               TEXT         NULL,
  activo              BOOLEAN      NOT NULL DEFAULT TRUE,
  fecha_creacion      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_cliente_email ON clientes (lower(email)) WHERE email IS NOT NULL AND email <> '';
CREATE UNIQUE INDEX ux_cliente_telefono ON clientes (telefono) WHERE telefono IS NOT NULL AND telefono <> '';
CREATE INDEX idx_cliente_nombre ON clientes (nombre, apellidos);
CREATE TRIGGER trg_clientes_upd BEFORE UPDATE ON clientes
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE direcciones (
  direccion_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id           INT NOT NULL REFERENCES clientes(cliente_id) ON DELETE CASCADE,
  tipo                 tipo_direccion NOT NULL DEFAULT 'domicilio',
  alias                VARCHAR(60)  NULL,
  calle                VARCHAR(255) NOT NULL,
  numero_exterior      VARCHAR(20)  NOT NULL DEFAULT '',
  numero_interior      VARCHAR(20)  NULL,
  colonia              VARCHAR(120) NULL,
  delegacion_municipio VARCHAR(120) NULL,
  ciudad               VARCHAR(120) NOT NULL,
  estado               VARCHAR(120) NOT NULL,
  pais                 VARCHAR(120) NOT NULL DEFAULT 'México',
  codigo_postal        VARCHAR(10)  NOT NULL,
  latitud              NUMERIC(10,8) NULL,
  longitud             NUMERIC(11,8) NULL,
  telefono_contacto    VARCHAR(20)  NULL,
  destinatario         VARCHAR(200) NULL,
  instrucciones        TEXT         NULL,
  ventana_hora_inicio  TIME         NULL,
  ventana_hora_fin     TIME         NULL,
  activo               BOOLEAN      NOT NULL DEFAULT TRUE,
  fecha_creacion       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  fecha_actualizacion  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_direccion_cliente ON direcciones (cliente_id);
CREATE INDEX idx_direccion_cp ON direcciones (codigo_postal);
CREATE TRIGGER trg_direcciones_upd BEFORE UPDATE ON direcciones
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

-- =============================================================================
-- Catálogo
-- =============================================================================
CREATE TABLE servicios (
  servicio_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre                  VARCHAR(120) NOT NULL,
  descripcion             TEXT NOT NULL DEFAULT '',
  precio                  NUMERIC(10,2) NOT NULL CHECK (precio >= 0),
  tiempo_estimado_minutos INT NOT NULL DEFAULT 60 CHECK (tiempo_estimado_minutos > 0),
  requiere_identificacion BOOLEAN NOT NULL DEFAULT FALSE,
  imagen_url              VARCHAR(500) NULL,
  activo                  BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion          TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_servicio_activo ON servicios (activo);
CREATE TRIGGER trg_servicios_upd BEFORE UPDATE ON servicios
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE categorias_productos (
  categoria_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              VARCHAR(120) NOT NULL UNIQUE,
  descripcion         TEXT NULL,
  activo              BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_categorias_upd BEFORE UPDATE ON categorias_productos
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE productos (
  producto_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id        INT NOT NULL REFERENCES categorias_productos(categoria_id),
  nombre              VARCHAR(150) NOT NULL,
  descripcion         TEXT NOT NULL DEFAULT '',
  precio              NUMERIC(10,2) NOT NULL CHECK (precio >= 0),
  costo               NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (costo >= 0),
  stock               INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
  stock_minimo        INT NOT NULL DEFAULT 5 CHECK (stock_minimo >= 0),
  codigo_barras       VARCHAR(60) NULL,
  imagen_url          VARCHAR(500) NULL,
  activo              BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_producto_codigo_barras ON productos (codigo_barras)
  WHERE codigo_barras IS NOT NULL AND codigo_barras <> '';
CREATE INDEX idx_producto_nombre ON productos (nombre);
CREATE INDEX idx_producto_categoria ON productos (categoria_id);
CREATE TRIGGER trg_productos_upd BEFORE UPDATE ON productos
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE marcas (
  marca_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              VARCHAR(120) NOT NULL UNIQUE,
  descripcion         TEXT NULL,
  logo_url            VARCHAR(500) NULL,
  sitio_web           VARCHAR(500) NULL,
  activo              BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_marcas_upd BEFORE UPDATE ON marcas
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE modelos_calzado (
  modelo_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marca_id            INT NOT NULL REFERENCES marcas(marca_id),
  nombre              VARCHAR(120) NOT NULL,
  descripcion         TEXT NULL,
  imagen_url          VARCHAR(500) NULL,
  activo              BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (marca_id, nombre)
);
CREATE TRIGGER trg_modelos_upd BEFORE UPDATE ON modelos_calzado
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE estados_servicio (
  estado_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              VARCHAR(60) NOT NULL UNIQUE,
  descripcion         TEXT NULL,
  orden               INT NOT NULL,
  color               VARCHAR(7) NOT NULL DEFAULT '#000000',
  -- Si el cliente debe recibir aviso al entrar a este estado (FUN-04)
  notifica_cliente    BOOLEAN NOT NULL DEFAULT FALSE,
  es_final            BOOLEAN NOT NULL DEFAULT FALSE,
  activo              BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_estados_upd BEFORE UPDATE ON estados_servicio
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

-- Zonas de recolección: sale del código a la base (OPS-06)
CREATE TABLE zonas_cobertura (
  zona_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              VARCHAR(80) NOT NULL,
  cp_inicio           VARCHAR(10) NOT NULL,
  cp_fin              VARCHAR(10) NOT NULL,
  costo               NUMERIC(10,2) NOT NULL CHECK (costo >= 0),
  tiempo_estimado     VARCHAR(40) NOT NULL DEFAULT '',
  activo              BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (cp_inicio <= cp_fin)
);
CREATE TRIGGER trg_zonas_upd BEFORE UPDATE ON zonas_cobertura
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

-- Capacidad por día para reservas en línea (OPS-04)
CREATE TABLE capacidad_dia (
  fecha            DATE PRIMARY KEY,
  max_pares        INT NOT NULL CHECK (max_pares >= 0),
  cerrado          BOOLEAN NOT NULL DEFAULT FALSE,
  motivo           VARCHAR(200) NULL
);

-- =============================================================================
-- Órdenes
-- Una "reserva en línea" es una orden con origen='online'. No hay tabla
-- reservaciones separada: ese modelo paralelo causaba que las reservas nunca
-- aparecieran en el panel (FUN-03).
-- =============================================================================
CREATE TABLE ordenes (
  orden_id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_orden            VARCHAR(24) NOT NULL UNIQUE,
  -- Token de alta entropía para el seguimiento público. El codigo_orden es
  -- corto y legible para el mostrador; este es el que no se puede adivinar.
  codigo_seguimiento      VARCHAR(64) NOT NULL UNIQUE,
  origen                  origen_orden NOT NULL DEFAULT 'pos',

  cliente_id              INT NOT NULL REFERENCES clientes(cliente_id),
  empleado_recepcion_id   INT NULL REFERENCES empleados(empleado_id),
  empleado_entrega_id     INT NULL REFERENCES empleados(empleado_id),
  direccion_id            INT NULL REFERENCES direcciones(direccion_id) ON DELETE SET NULL,

  -- Importes: se calculan SIEMPRE en el servidor (SEC-04).
  subtotal                NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  descuento               NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
  impuestos               NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (impuestos >= 0),
  total                   NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
  motivo_descuento        VARCHAR(200) NULL,
  descuento_autorizado_por INT NULL REFERENCES empleados(empleado_id),

  estado_actual_id        INT NOT NULL REFERENCES estados_servicio(estado_id),
  estado_pago             estado_pago_orden NOT NULL DEFAULT 'pendiente',
  metodo_pago             metodo_pago NULL,

  requiere_identificacion BOOLEAN NOT NULL DEFAULT FALSE,
  tiene_identificacion_registrada BOOLEAN NOT NULL DEFAULT FALSE,

  -- Recolección a domicilio
  requiere_pickup         BOOLEAN NOT NULL DEFAULT FALSE,
  costo_pickup            NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (costo_pickup >= 0),
  zona_pickup             VARCHAR(80) NULL,

  fecha_reservacion       TIMESTAMPTZ NULL,   -- franja solicitada (online)
  fecha_recepcion         TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_entrega_estimada  TIMESTAMPTZ NOT NULL,
  fecha_entrega_real      TIMESTAMPTZ NULL,

  -- Cancelación (OPS-03)
  cancelada               BOOLEAN NOT NULL DEFAULT FALSE,
  cancelada_en            TIMESTAMPTZ NULL,
  cancelada_por           INT NULL REFERENCES empleados(empleado_id),
  motivo_cancelacion      TEXT NULL,

  -- Consentimiento
  acepta_terminos         BOOLEAN NOT NULL DEFAULT FALSE,
  acepta_whatsapp         BOOLEAN NOT NULL DEFAULT FALSE,
  consent_at              TIMESTAMPTZ NULL,

  notas                   TEXT NULL,
  fecha_creacion          TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CHECK (total >= 0),
  CHECK (NOT cancelada OR cancelada_en IS NOT NULL)
);
CREATE INDEX idx_orden_cliente        ON ordenes (cliente_id);
CREATE INDEX idx_orden_fecha_recepcion ON ordenes (fecha_recepcion DESC);
CREATE INDEX idx_orden_estado         ON ordenes (estado_actual_id);
CREATE INDEX idx_orden_estado_pago    ON ordenes (estado_pago);
CREATE INDEX idx_orden_origen         ON ordenes (origen);
CREATE INDEX idx_orden_codigo_trgm    ON ordenes (codigo_orden varchar_pattern_ops);
CREATE TRIGGER trg_ordenes_upd BEFORE UPDATE ON ordenes
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

-- Un renglón = UN PAR de tenis. Nunca se agrupan pares con detalle de calzado.
CREATE TABLE detalles_orden_servicios (
  detalle_servicio_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id            INT NOT NULL REFERENCES ordenes(orden_id) ON DELETE CASCADE,
  servicio_id         INT NOT NULL REFERENCES servicios(servicio_id),
  cantidad            INT NOT NULL DEFAULT 1 CHECK (cantidad > 0),
  precio_unitario     NUMERIC(10,2) NOT NULL CHECK (precio_unitario >= 0),
  descuento           NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
  subtotal            NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),

  -- Identificación del par
  modelo_id           INT NULL REFERENCES modelos_calzado(modelo_id),
  marca               VARCHAR(120) NULL,
  modelo              VARCHAR(120) NULL,
  talla               VARCHAR(20)  NULL,
  color               VARCHAR(60)  NULL,
  descripcion_calzado TEXT NULL,

  -- Ubicación física en almacén
  caja_almacenamiento VARCHAR(40) NULL,
  codigo_ubicacion    VARCHAR(40) NULL,
  notas_especiales    TEXT NULL,

  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_detalle_servicio_orden ON detalles_orden_servicios (orden_id);
CREATE INDEX idx_detalle_ubicacion ON detalles_orden_servicios (caja_almacenamiento, codigo_ubicacion)
  WHERE codigo_ubicacion IS NOT NULL;
-- Un código de ubicación solo puede estar ocupado por un par a la vez.
-- Al entregar se limpia la ubicación, de modo que el espacio se reutiliza (FUN-09).
CREATE UNIQUE INDEX ux_ubicacion_ocupada ON detalles_orden_servicios (codigo_ubicacion)
  WHERE codigo_ubicacion IS NOT NULL;
CREATE TRIGGER trg_det_serv_upd BEFORE UPDATE ON detalles_orden_servicios
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE detalles_orden_productos (
  detalle_producto_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id            INT NOT NULL REFERENCES ordenes(orden_id) ON DELETE CASCADE,
  producto_id         INT NOT NULL REFERENCES productos(producto_id),
  cantidad            INT NOT NULL CHECK (cantidad > 0),
  precio_unitario     NUMERIC(10,2) NOT NULL CHECK (precio_unitario >= 0),
  descuento           NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
  subtotal            NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_detalle_producto_orden ON detalles_orden_productos (orden_id);
CREATE TRIGGER trg_det_prod_upd BEFORE UPDATE ON detalles_orden_productos
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE costos_adicionales_orden (
  costo_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id       INT NOT NULL REFERENCES ordenes(orden_id) ON DELETE CASCADE,
  concepto       VARCHAR(60) NOT NULL,
  descripcion    TEXT NULL,
  monto          NUMERIC(10,2) NOT NULL CHECK (monto >= 0),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_costo_adicional_orden ON costos_adicionales_orden (orden_id);

CREATE TABLE historial_estados (
  historial_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id       INT NOT NULL REFERENCES ordenes(orden_id) ON DELETE CASCADE,
  estado_id      INT NOT NULL REFERENCES estados_servicio(estado_id),
  empleado_id    INT NULL REFERENCES empleados(empleado_id),
  comentario     TEXT NULL,
  fecha_cambio   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_historial_orden ON historial_estados (orden_id, fecha_cambio DESC);

CREATE TABLE historial_ubicaciones (
  ubicacion_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  detalle_servicio_id INT NOT NULL REFERENCES detalles_orden_servicios(detalle_servicio_id) ON DELETE CASCADE,
  orden_id            INT NOT NULL REFERENCES ordenes(orden_id) ON DELETE CASCADE,
  caja_almacenamiento VARCHAR(40) NULL,
  codigo_ubicacion    VARCHAR(40) NULL,
  notas               TEXT NULL,
  accion              VARCHAR(20) NOT NULL DEFAULT 'asignada',
  empleado_id         INT NULL REFERENCES empleados(empleado_id),
  fecha_asignacion    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_hist_ubic_detalle ON historial_ubicaciones (detalle_servicio_id, fecha_asignacion DESC);

-- =============================================================================
-- Caja y pagos
-- =============================================================================
CREATE TABLE cortes_caja (
  corte_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empleado_id         INT NOT NULL REFERENCES empleados(empleado_id),
  estado              estado_corte NOT NULL DEFAULT 'abierto',
  fondo_inicial       NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (fondo_inicial >= 0),
  abierto_en          TIMESTAMPTZ NOT NULL DEFAULT now(),
  cerrado_en          TIMESTAMPTZ NULL,
  cerrado_por         INT NULL REFERENCES empleados(empleado_id),
  efectivo_declarado  NUMERIC(10,2) NULL,
  efectivo_esperado   NUMERIC(10,2) NULL,
  diferencia          NUMERIC(10,2) NULL,
  notas               TEXT NULL
);
CREATE INDEX idx_corte_empleado ON cortes_caja (empleado_id, abierto_en DESC);
-- Un empleado no puede tener dos cajas abiertas a la vez.
CREATE UNIQUE INDEX ux_corte_abierto ON cortes_caja (empleado_id) WHERE estado = 'abierto';

CREATE TABLE pagos (
  pago_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id          INT NOT NULL REFERENCES ordenes(orden_id) ON DELETE CASCADE,
  -- monto = lo que se aplica a la orden. NUNCA el billete recibido (DAT-06).
  monto             NUMERIC(10,2) NOT NULL CHECK (monto <> 0),
  efectivo_recibido NUMERIC(10,2) NULL CHECK (efectivo_recibido >= 0),
  cambio_entregado  NUMERIC(10,2) NULL CHECK (cambio_entregado >= 0),
  metodo            metodo_pago NOT NULL,
  referencia        VARCHAR(120) NULL,
  terminal_id       VARCHAR(60)  NULL,
  empleado_id       INT NOT NULL REFERENCES empleados(empleado_id),
  corte_id          INT NULL REFERENCES cortes_caja(corte_id),
  estado            estado_pago NOT NULL DEFAULT 'completado',
  -- Un reembolso es un pago negativo que apunta al pago original (OPS-03)
  pago_original_id  INT NULL REFERENCES pagos(pago_id),
  motivo            TEXT NULL,
  fecha_pago        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_pago_orden   ON pagos (orden_id);
CREATE INDEX idx_pago_fecha   ON pagos (fecha_pago DESC);
CREATE INDEX idx_pago_corte   ON pagos (corte_id) WHERE corte_id IS NOT NULL;
CREATE INDEX idx_pago_empleado ON pagos (empleado_id, fecha_pago DESC);

-- =============================================================================
-- Inventario
-- =============================================================================
CREATE TABLE inventario_movimientos (
  movimiento_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id      INT NOT NULL REFERENCES productos(producto_id),
  tipo_movimiento  tipo_movimiento_inv NOT NULL,
  cantidad         INT NOT NULL,
  stock_anterior   INT NOT NULL,
  stock_nuevo      INT NOT NULL CHECK (stock_nuevo >= 0),
  orden_id         INT NULL REFERENCES ordenes(orden_id) ON DELETE SET NULL,
  empleado_id      INT NOT NULL REFERENCES empleados(empleado_id),
  motivo           TEXT NULL,
  fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_movimiento_producto ON inventario_movimientos (producto_id, fecha_movimiento DESC);
CREATE INDEX idx_movimiento_fecha ON inventario_movimientos (fecha_movimiento DESC);

-- =============================================================================
-- Archivos, mensajería, configuración
-- =============================================================================
CREATE TABLE archivos_media (
  archivo_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo                tipo_archivo NOT NULL,
  entidad_tipo        entidad_archivo NOT NULL,
  entidad_id          INT NOT NULL,
  -- Ancla al par exacto cuando se trata de fotos de calzado (FUN-01)
  detalle_servicio_id INT NULL REFERENCES detalles_orden_servicios(detalle_servicio_id) ON DELETE SET NULL,
  nombre_archivo      VARCHAR(255) NOT NULL,
  extension           VARCHAR(10)  NOT NULL,
  tamano              INT NOT NULL CHECK (tamano > 0),
  content_type        VARCHAR(120) NOT NULL DEFAULT 'application/octet-stream',
  s3_bucket           VARCHAR(120) NOT NULL,
  -- Solo se guarda la llave. La URL se firma al momento de servirla (SEC-09).
  s3_key              VARCHAR(500) NOT NULL,
  descripcion         TEXT NULL,
  es_publico          BOOLEAN NOT NULL DEFAULT FALSE,
  empleado_id         INT NULL REFERENCES empleados(empleado_id),
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_archivo_entidad ON archivos_media (entidad_tipo, entidad_id);
CREATE INDEX idx_archivo_detalle ON archivos_media (detalle_servicio_id) WHERE detalle_servicio_id IS NOT NULL;
CREATE TRIGGER trg_archivos_upd BEFORE UPDATE ON archivos_media
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE mensajes_contacto (
  mensaje_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              VARCHAR(255) NOT NULL,
  email               VARCHAR(255) NOT NULL,
  telefono            VARCHAR(30) NULL,
  asunto              VARCHAR(500) NOT NULL,
  mensaje             TEXT NOT NULL,
  esta_leido          BOOLEAN NOT NULL DEFAULT FALSE,
  esta_destacado      BOOLEAN NOT NULL DEFAULT FALSE,
  esta_archivado      BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_mensaje_fecha ON mensajes_contacto (fecha_creacion DESC);
CREATE INDEX idx_mensaje_no_leido ON mensajes_contacto (esta_leido) WHERE NOT esta_leido;
CREATE TRIGGER trg_mensajes_upd BEFORE UPDATE ON mensajes_contacto
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE respuestas_mensajes (
  respuesta_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mensaje_id     INT NOT NULL REFERENCES mensajes_contacto(mensaje_id) ON DELETE CASCADE,
  empleado_id    INT NULL REFERENCES empleados(empleado_id),
  asunto         VARCHAR(500) NOT NULL,
  cuerpo         TEXT NOT NULL,
  enviado_a      VARCHAR(255) NOT NULL,
  enviado_en     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_respuesta_mensaje ON respuestas_mensajes (mensaje_id, enviado_en DESC);

CREATE TABLE configuracion_sistema (
  config_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave               VARCHAR(120) NOT NULL UNIQUE,
  valor               TEXT NOT NULL,
  descripcion         TEXT NULL,
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_config_upd BEFORE UPDATE ON configuracion_sistema
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE registro_actividad (
  log_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id       INT NULL REFERENCES usuarios(usuario_id) ON DELETE SET NULL,
  tabla_afectada   VARCHAR(120) NOT NULL,
  accion           accion_log NOT NULL,
  registro_id      INT NULL,
  datos_anteriores JSONB NULL,
  datos_nuevos     JSONB NULL,
  ip_usuario       VARCHAR(45) NULL,
  user_agent       TEXT NULL,
  fecha_accion     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_log_fecha ON registro_actividad (fecha_accion DESC);
CREATE INDEX idx_log_tabla ON registro_actividad (tabla_afectada, registro_id);

-- Límite de peticiones sin depender de un servicio externo (SEC-08)
CREATE TABLE rate_limit (
  bucket      VARCHAR(200) PRIMARY KEY,
  golpes      INT NOT NULL DEFAULT 0,
  ventana_fin TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_rate_limit_ventana ON rate_limit (ventana_fin);

CREATE TABLE preguntas_frecuentes (
  pregunta_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pregunta            TEXT NOT NULL,
  respuesta           TEXT NOT NULL,
  orden               INT NOT NULL DEFAULT 0,
  activo              BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_faq_upd BEFORE UPDATE ON preguntas_frecuentes
  FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

-- =============================================================================
-- Vistas
-- Nota: todos los JOIN a empleados son LEFT. Con INNER, desactivar un empleado
-- hacía desaparecer sus órdenes del panel entero (DAT-04).
-- =============================================================================
CREATE VIEW vw_ordenes_detalle AS
SELECT
  o.orden_id, o.codigo_orden, o.codigo_seguimiento, o.origen,
  o.cliente_id,
  c.nombre AS cliente_nombre, c.apellidos AS cliente_apellidos,
  c.telefono AS cliente_telefono, c.email AS cliente_email,
  o.empleado_recepcion_id, o.empleado_entrega_id,
  NULLIF(TRIM(CONCAT_WS(' ', er.nombre, er.apellidos)), '') AS empleado_recepcion,
  NULLIF(TRIM(CONCAT_WS(' ', ee.nombre, ee.apellidos)), '') AS empleado_entrega,
  o.estado_actual_id,
  es.nombre AS estado_servicio, es.color AS color_estado, es.orden AS estado_orden,
  es.es_final AS estado_es_final,
  o.subtotal, o.descuento, o.impuestos, o.total,
  o.estado_pago, o.metodo_pago,
  COALESCE(pg.total_pagado, 0)                 AS total_pagado,
  o.total - COALESCE(pg.total_pagado, 0)       AS saldo_pendiente,
  o.requiere_identificacion, o.tiene_identificacion_registrada,
  o.requiere_pickup, o.costo_pickup, o.zona_pickup, o.direccion_id,
  o.fecha_reservacion, o.fecha_recepcion, o.fecha_entrega_estimada, o.fecha_entrega_real,
  o.cancelada, o.cancelada_en, o.motivo_cancelacion,
  o.acepta_terminos, o.acepta_whatsapp, o.consent_at,
  o.notas, o.fecha_creacion, o.fecha_actualizacion,
  (SELECT COUNT(*) FROM detalles_orden_servicios d WHERE d.orden_id = o.orden_id) AS total_pares
FROM ordenes o
JOIN clientes c          ON c.cliente_id = o.cliente_id
LEFT JOIN empleados er   ON er.empleado_id = o.empleado_recepcion_id
LEFT JOIN empleados ee   ON ee.empleado_id = o.empleado_entrega_id
JOIN estados_servicio es ON es.estado_id = o.estado_actual_id
LEFT JOIN (
  SELECT orden_id, SUM(monto) AS total_pagado
  FROM pagos WHERE estado = 'completado'
  GROUP BY orden_id
) pg ON pg.orden_id = o.orden_id;

CREATE VIEW vw_detalles_orden_servicios AS
SELECT
  d.detalle_servicio_id, d.orden_id, d.servicio_id,
  s.nombre AS servicio_nombre, s.descripcion AS servicio_descripcion,
  s.tiempo_estimado_minutos,
  d.cantidad, d.precio_unitario, d.descuento, d.subtotal,
  d.modelo_id, d.marca, d.modelo, d.talla, d.color, d.descripcion_calzado,
  d.caja_almacenamiento, d.codigo_ubicacion, d.notas_especiales,
  m.nombre AS modelo_catalogo, mk.nombre AS marca_catalogo,
  (SELECT COUNT(*) FROM archivos_media a
    WHERE a.detalle_servicio_id = d.detalle_servicio_id
      AND a.tipo IN ('calzado_entrada','calzado_salida')) AS total_fotos,
  d.fecha_creacion
FROM detalles_orden_servicios d
JOIN servicios s            ON s.servicio_id = d.servicio_id
LEFT JOIN modelos_calzado m ON m.modelo_id = d.modelo_id
LEFT JOIN marcas mk         ON mk.marca_id = m.marca_id;

CREATE VIEW vw_detalles_orden_productos AS
SELECT
  d.detalle_producto_id, d.orden_id, d.producto_id,
  p.nombre AS producto_nombre, p.descripcion AS producto_descripcion,
  p.codigo_barras, cat.nombre AS categoria,
  d.cantidad, d.precio_unitario, d.descuento, d.subtotal, d.fecha_creacion
FROM detalles_orden_productos d
JOIN productos p            ON p.producto_id = d.producto_id
JOIN categorias_productos cat ON cat.categoria_id = p.categoria_id;

CREATE VIEW vw_historial_estados AS
SELECT
  h.historial_id, h.orden_id, h.estado_id,
  e.nombre AS estado_nombre, e.color AS estado_color, e.orden AS estado_orden,
  h.empleado_id,
  NULLIF(TRIM(CONCAT_WS(' ', emp.nombre, emp.apellidos)), '') AS empleado_nombre,
  h.comentario, h.fecha_cambio
FROM historial_estados h
JOIN estados_servicio e ON e.estado_id = h.estado_id
LEFT JOIN empleados emp ON emp.empleado_id = h.empleado_id;

CREATE VIEW vw_inventario_actual AS
SELECT
  p.producto_id, p.nombre AS producto_nombre, p.nombre, p.descripcion,
  p.categoria_id, cat.nombre AS categoria,
  p.precio, p.costo, p.stock, p.stock_minimo, p.codigo_barras, p.activo,
  (p.stock * p.costo)  AS valor_inventario,
  (p.stock <= p.stock_minimo) AS stock_bajo,
  (p.stock = 0)        AS agotado
FROM productos p
JOIN categorias_productos cat ON cat.categoria_id = p.categoria_id;

CREATE VIEW vw_movimientos_inventario AS
SELECT
  m.movimiento_id, m.producto_id, p.nombre AS producto_nombre, p.codigo_barras,
  m.tipo_movimiento, m.cantidad, m.stock_anterior, m.stock_nuevo,
  m.orden_id, o.codigo_orden,
  m.empleado_id,
  NULLIF(TRIM(CONCAT_WS(' ', e.nombre, e.apellidos)), '') AS empleado_nombre,
  m.motivo, m.fecha_movimiento
FROM inventario_movimientos m
JOIN productos p     ON p.producto_id = m.producto_id
LEFT JOIN ordenes o  ON o.orden_id = m.orden_id
LEFT JOIN empleados e ON e.empleado_id = m.empleado_id;

CREATE VIEW vw_mapa_ubicaciones AS
SELECT
  d.caja_almacenamiento, d.codigo_ubicacion, d.detalle_servicio_id,
  d.orden_id, o.codigo_orden, o.fecha_recepcion, o.fecha_entrega_estimada,
  d.marca, d.modelo, d.talla, d.color, d.descripcion_calzado, d.notas_especiales,
  s.nombre AS servicio_nombre,
  NULLIF(TRIM(CONCAT_WS(' ', c.nombre, c.apellidos)), '') AS cliente,
  c.telefono AS cliente_telefono,
  es.nombre AS estado_orden, es.color AS estado_color,
  (o.fecha_entrega_estimada < now() AND NOT es.es_final) AS retrasada
FROM detalles_orden_servicios d
JOIN ordenes o           ON o.orden_id = d.orden_id
JOIN clientes c          ON c.cliente_id = o.cliente_id
JOIN servicios s         ON s.servicio_id = d.servicio_id
JOIN estados_servicio es ON es.estado_id = o.estado_actual_id
WHERE d.codigo_ubicacion IS NOT NULL AND NOT o.cancelada;

CREATE VIEW vw_ordenes_entrega_hoy AS
SELECT * FROM vw_ordenes_detalle
WHERE fecha_entrega_estimada::date = CURRENT_DATE
  AND NOT cancelada AND NOT estado_es_final;

CREATE VIEW vw_ordenes_id_pendiente AS
SELECT * FROM vw_ordenes_detalle
WHERE requiere_identificacion AND NOT tiene_identificacion_registrada AND NOT cancelada;

CREATE VIEW vw_servicios_populares AS
SELECT
  s.servicio_id, s.nombre, s.precio,
  COUNT(d.detalle_servicio_id) AS total_vendidos,
  COALESCE(SUM(d.subtotal), 0) AS ingresos
FROM servicios s
LEFT JOIN detalles_orden_servicios d ON d.servicio_id = s.servicio_id
LEFT JOIN ordenes o ON o.orden_id = d.orden_id AND NOT o.cancelada
GROUP BY s.servicio_id, s.nombre, s.precio
ORDER BY total_vendidos DESC;

CREATE VIEW vw_productos_populares AS
SELECT
  p.producto_id, p.nombre, p.precio,
  COALESCE(SUM(d.cantidad), 0) AS total_vendidos,
  COALESCE(SUM(d.subtotal), 0) AS ingresos
FROM productos p
LEFT JOIN detalles_orden_productos d ON d.producto_id = p.producto_id
LEFT JOIN ordenes o ON o.orden_id = d.orden_id AND NOT o.cancelada
GROUP BY p.producto_id, p.nombre, p.precio
ORDER BY total_vendidos DESC;

CREATE VIEW vw_estadisticas_ventas_mensuales AS
SELECT
  date_trunc('month', o.fecha_recepcion)::date AS mes,
  to_char(o.fecha_recepcion, 'YYYY-MM')        AS periodo,
  COUNT(*)                                      AS total_ordenes,
  COALESCE(SUM(o.subtotal), 0)                  AS subtotal,
  COALESCE(SUM(o.impuestos), 0)                 AS impuestos,
  COALESCE(SUM(o.total), 0)                     AS total,
  COALESCE(AVG(o.total), 0)                     AS ticket_promedio
FROM ordenes o
WHERE NOT o.cancelada
GROUP BY 1, 2
ORDER BY 1 DESC;

CREATE VIEW vw_reporte_empleados AS
SELECT
  e.empleado_id,
  NULLIF(TRIM(CONCAT_WS(' ', e.nombre, e.apellidos)), '') AS empleado_nombre,
  e.puesto, e.activo,
  COALESCE(ord.ordenes_recibidas, 0) AS ordenes_recibidas,
  COALESCE(ord.total_vendido, 0)     AS total_vendido,
  COALESCE(pay.pagos_registrados, 0) AS pagos_registrados,
  COALESCE(pay.monto_cobrado, 0)     AS monto_cobrado
FROM empleados e
LEFT JOIN (
  SELECT empleado_recepcion_id AS empleado_id,
         COUNT(*) AS ordenes_recibidas,
         SUM(total) AS total_vendido
  FROM ordenes WHERE NOT cancelada
  GROUP BY empleado_recepcion_id
) ord ON ord.empleado_id = e.empleado_id
LEFT JOIN (
  SELECT empleado_id,
         COUNT(*) AS pagos_registrados,
         SUM(monto) AS monto_cobrado
  FROM pagos WHERE estado = 'completado'
  GROUP BY empleado_id
) pay ON pay.empleado_id = e.empleado_id;

-- =============================================================================
-- Datos iniciales
-- =============================================================================
INSERT INTO estados_servicio (estado_id, nombre, descripcion, orden, color, notifica_cliente, es_final) VALUES
  (1, 'Pendiente',          'Reserva en línea, aún no llega el calzado',    0, '#94a3b8', FALSE, FALSE),
  (2, 'Recibido',           'El calzado fue recibido en sucursal',          1, '#3498db', TRUE,  FALSE),
  (3, 'En proceso',         'El calzado está siendo procesado',             2, '#f39c12', FALSE, FALSE),
  (4, 'Lavando',            'El calzado está en proceso de lavado',         3, '#2ecc71', FALSE, FALSE),
  (5, 'Secando',            'El calzado está en proceso de secado',         4, '#9b59b6', FALSE, FALSE),
  (6, 'Control de calidad', 'Verificación final del calzado',               5, '#e74c3c', FALSE, FALSE),
  (7, 'Listo para entrega', 'El calzado está listo para ser recogido',      6, '#1abc9c', TRUE,  FALSE),
  (8, 'Entregado',          'El calzado fue entregado al cliente',          7, '#34495e', TRUE,  TRUE),
  (9, 'Cancelada',          'La orden fue cancelada',                       8, '#7f1d1d', TRUE,  TRUE);
SELECT setval(pg_get_serial_sequence('estados_servicio','estado_id'), 9, true);

INSERT INTO configuracion_sistema (clave, valor, descripcion) VALUES
  ('iva_porcentaje',            '16',    'Porcentaje de IVA aplicable'),
  ('precios_incluyen_iva',      'true',  'Si los precios del catálogo ya incluyen IVA'),
  ('precio_minimo_requiere_id', '1000',  'Monto a partir del cual se solicita identificación'),
  ('descuento_maximo',          '20',    'Descuento máximo permitido en porcentaje'),
  ('dias_procesamiento',        '3',     'Días hábiles estimados de procesamiento'),
  ('capacidad_diaria_default',  '30',    'Pares máximos por día para reservas en línea'),
  ('horario_apertura',          '10:00', 'Hora de apertura'),
  ('horario_cierre',            '19:00', 'Hora de cierre'),
  ('dias_operacion',            'lunes,martes,miercoles,jueves,viernes,sabado', 'Días con servicio'),
  ('nombre_empresa',            'VIP Cleaners', 'Nombre comercial'),
  ('telefono_contacto',         '',      'Teléfono de contacto principal'),
  ('email_contacto',            '',      'Correo de contacto principal'),
  ('direccion_empresa',         '',      'Dirección física'),
  ('website_empresa',           '',      'Sitio web'),
  ('notificaciones_email',      'true',  'Enviar avisos por correo al cliente'),
  ('notificaciones_whatsapp',   'false', 'Enviar avisos por WhatsApp al cliente'),
  ('timezone',                  'America/Mexico_City', 'Zona horaria del negocio'),
  ('moneda',                    'MXN',   'Moneda de operación');

INSERT INTO zonas_cobertura (nombre, cp_inicio, cp_fin, costo, tiempo_estimado) VALUES
  ('Centro', '76000', '76099', 49, '30-45 min'),
  ('Norte',  '76100', '76199', 69, '45-60 min'),
  ('Sur',    '76200', '76299', 79, '50-65 min'),
  ('Este',   '76300', '76399', 59, '35-50 min'),
  ('Oeste',  '76400', '76499', 64, '40-55 min');

INSERT INTO categorias_productos (nombre, descripcion) VALUES
  ('Limpieza',   'Productos de limpieza para calzado'),
  ('Protección', 'Impermeabilizantes y protectores'),
  ('Accesorios', 'Agujetas, plantillas y accesorios');
